#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import sys
import json
import agent
import random
import string

request = json.load(sys.stdin)
data = dict()

data['host'] = request.get('host')
data['contact_site'] = request.get('contact_site', 'https://www.nethserver.org')
data['logo_url'] = request.get('logo_url', '')
data['title'] = request.get('title', 'Registry')
data['description'] = request.get('description', '')
data['superuser'] = request.get('superuser', 'admin') 
data['secret'] = '';

# Generete secret if not exists
secret_file = 'db.secret'
if os.path.isfile(secret_file):
    with open(secret_file) as x: data['secret'] = x.read()
else:
    data['secret'] = ''.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits) for _ in range(16))
    with open(secret_file, 'w') as s:
        s.write(data['secret'])

# To enable github, add the following to the config file:
# 
# FEATURE_GITHUB_LOGIN: true
# GITHUB_LOGIN_CONFIG:
#    API_ENDPOINT: https://api.github.com/
#    CLIENT_ID: xxxxxxxxxxxxxxxxxxxx
#    CLIENT_SECRET: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#    GITHUB_ENDPOINT: https://github.com/
#    ORG_RESTRICT: false

config = ""
with open('config.yaml.template', 'r') as f:
    src = string.Template(f.read())
    config = src.substitute(data)

with open('config.yaml', 'w') as cf:
    cf.write(config)
